# Generated by Django 3.2.9 on 2022-03-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220308_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='status',
        ),
    ]
